### ISSUE TITLE
Nearest Neighbours in Cosine distance

### ISSUE THREAD

**Issue by shixing** [pixelogik/NearPy#19]
A vector V is hashed into a bucket B, the V is compared with all vectors in B. This only bucket B usually leads to bad performance.

A good way to solve it is to find several closest neighbour buckets in term of hamming distance. e.g. B= "1001", the neighbour buckets could be "1000" ,"1011" ... Then compare V with all vectors in these buckets.

How do you think about it ? I've implemented an extension class based on your class Engine and would like to incorporate into your code.

Thanks,
Xing

**Comment by bduffany** [comment]
Could someone post a link to the paper that was attached via e-mail (mentioned way early in this thread)? I'd really like to take a look at it :)

**Comment by shixing** [comment]
Here it is https://www.cs.cmu.edu/~hovy/papers/05ACL-clustering.pdf

On Fri, Dec 11, 2015 at 12:36 PM, Brandon Duffany <notifications@github.com>
wrote:

> Could someone post a link to the paper that was attached via e-mail
> (mentioned way early in this thread)? I'd really like to take a look at it
> :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pixelogik/NearPy/issues/19#issuecomment-164041723>.
>



-- 

--

Xing Shi  史 兴

PhD Candidate

Department of Computer Science

University of Southern California

Los Angeles, CA, 90007

Home Page: xingshi.me
