### ISSUE TITLE
Start a real documentation of the library

### ISSUE THREAD

**Issue by pixelogik** [pixelogik/NearPy#23]
With detailed description of the components, tutorials, examples, etc...

**Comment by Naereen** [comment]
This would be great indeed. Any chance of starting it ?

**Comment by pixelogik** [comment]
Not soon, sorry.

**Comment by Naereen** [comment]
OK.
If you ever start, do not hesitate to ask for help, I might have time to assist you!
Anyway, thanks for your cool and well written project!

Regards.

**Comment by pixelogik** [comment]
Will do. Thanks!!

**Comment by adityapatadia** [comment]
@Naereen If you want to help, you can now send PRs. I will ensure that they are merged.

**Comment by Naereen** [comment]
Sorry, I won't have time to do it myself alone :cry:.

**Comment by adityapatadia** [comment]
This is what we have so far: http://pixelogik.github.io/NearPy/ I also don't have much time but the doc seems enough to get started. Let's hope support will pour in future.

**Comment by pixelogik** [comment]
Guys, so sorry that I am off on this. Awesome that you take over for now! I hope NearPy is of good use.
