### ISSUE TITLE
When set distance=None, it actually still assign a distance function

### ISSUE THREAD

**Issue by huapeek** [pixelogik/NearPy#34]
If I explicitly set the distance=None in the __init__, why it still set a cos distance function? Should it be just None. If I didn't set any value there, then set a default distance function. Otherwise, I have to set it again using engine.distance = None.

**Comment by pixelogik** [comment]
Oh yeah, that does not make sense. Because the engine can function without a distance. Thanks for pointing that out.

**Comment by adityapatadia** [comment]
@huapeek PR will be appreciated.
