### ISSUE TITLE
Upgrade version available in pip

### ISSUE THREAD

**Issue by adityapatadia** [pixelogik/NearPy#46]
The version available in pip is not compatible with python3. Please push new compatible version.

Thanks.

**Comment by wanderer2** [comment]
Seconded. Thanks in advance.

**Comment by adityapatadia** [comment]
Is anyone maintaining this project? If help is needed to maintain this project, I can offer my axe.

**Comment by pixelogik** [comment]
@adityapatadia  Currently not really. Help would actually be very welcomed. Do you want to be a contributor?

**Comment by adityapatadia** [comment]
I would love to be. Let me know how would you like to take this ahead. We would also need to push newer versions to PIP, lets figure out how can we manage it.

**Comment by adityapatadia** [comment]
Can you update on this?

**Comment by pixelogik** [comment]
Yeah sorry. So busy. I can just make you a collaborator. Will do that now.

**Comment by adityapatadia** [comment]
How to publish new version to PIP? Is there any access required for the same?

**Comment by pixelogik** [comment]
Unfortunately I dont see a way to add somebody to the NearPy package on pypi. So I have to release that.

**Comment by joosep-wm** [comment]
Any news regarding fix for Python 3?
I'm getting this error with Python 3
http://pastebin.com/UP7JBw3W

**Comment by pixelogik** [comment]
Hm I should release a new version on PyPi I guess.

**Comment by adityapatadia** [comment]
@pixelogik if you can run tests and update new version, that would be great. If you are too busy, may be you can share credentials for the pip to me and I will take care of it.

**Comment by pixelogik** [comment]
@adityapatadia That would be great actually. Could you write me an email to ole@pixelogik.de and we manage some skype chat or something?

**Comment by adityapatadia** [comment]
@pixelogik Mailed you from personal mail id.
