### ISSUE TITLE
multiple hash tables

### ISSUE THREAD

**Issue by armintabari** [pixelogik/NearPy#47]
In LSH there are two factors that affect the accuracy, the number of bits in the code (projections) and the number of hash tables.
When you create an engin like:
 
_rbp = RandomBinaryProjections('rbp', 10)
engine = Engine(dimension, lshashes=[rbp])_

Does it only do one time random projection?
Can we redo the hashing multiple times to increase the accuracy?

**Comment by pixelogik** [comment]
Yes you are right. That is why you can provide as may hashes as you want in the lshashes parameter. 

engine = Engine(dimension, lshashes=[rbp1, rbp2, rbp3, rbp4, rbp5])

would use five hashes. Is that what you meant?

**Comment by armintabari** [comment]
So by passing 5 hashes to the engine it would run 5 times and compare them to increase accuracy? if yes, then that is exactly what I mean.
