### ISSUE TITLE
Number of returned neighbors

### ISSUE THREAD

**Issue by armintabari** [pixelogik/NearPy#49]
I have this problem that I always get 10 results from the engine.neighbours() function. It doesn't matter how many projections I have of what is the bucket size. 

Am I missing something? Could not find any setting on number of neighbors returned.

**Comment by amorgun** [comment]
By default it returns 10 nearest neighbours, [here](https://github.com/pixelogik/NearPy/blob/master/nearpy/engine.py#L73) is the default filters setup. You need to pass custom `vector_filters` in order to get other number of neighbours.
