### ISSUE TITLE
engine.store_vector

### ISSUE THREAD

**Issue by armintabari** [pixelogik/NearPy#50]
For a large number of vectors, it takes a long time to call "engine.store_vector()" for all the data points.
Is there faster way to index the vectors?  

BTW, thank you for answering quickly.

**Comment by amorgun** [comment]
@armintabari It's hard to answer without example code. E.g., if you are using `RedisStorage` you may tinker it to group multiple `store_vector` operations into one pipeline and get significant speedup.
