### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by mikluko** [pixelogik/NearPy#6]
I've done some work in this direction. Tets in `run_tests.py` are passing correctly. Pull request is coming.

**Comment by wbittremieux** [comment]
The HashPermutations hashes seem not to be Python 3 compatible. Specifically, there are some issues using `xrange`, which doesn't exist in Python 3.

Some of the issues are the following, although the list may not be complete as I didn't try to solve them:

* permutedIndex.py: line 81, 124
* permute.py: line 42, 54, 63

**Comment by pixelogik** [comment]
Thx. Might look into that at some point.
