### ISSUE TITLE
What are the plans for adding supports to store index data in mongo ?

### ISSUE THREAD

**Issue by RahulGupta-Reflektion** [pixelogik/NearPy#64]
I was using Redis to store index for index application. As Redis stores everything as string, this drives the memory usage up. 
Is anybody working on integrating mongo to store indexes?

**Comment by pixelogik** [comment]
@RahulGupta-Reflektion Nobody is working on this yet. 

Are you interested in working on this?

**Comment by xieqihui** [comment]
I have added supports for MongoDB in this PR.
https://github.com/pixelogik/NearPy/pull/72
Welcome to review and improve it.

**Comment by pixelogik** [comment]
Closing this ticket because we are working on the pull request #72 . Thanks for your request @RahulGupta-Reflektion !
