### ISSUE TITLE
Configure CI

### ISSUE THREAD

**Issue by amorgun** [pixelogik/NearPy#73]
After https://github.com/pixelogik/NearPy/pull/40 this repository works well with Travis CI so I suggest the following:
- Enable building of this project at https://travis-ci.org/pixelogik/NearPy
- Add badge to readme

**Comment by pixelogik** [comment]
@amorgun Yeah good point. Will try to do that soon.

**Comment by pixelogik** [comment]
@amorgun Done

**Comment by amorgun** [comment]
https://github.com/pixelogik/NearPy/commit/2c4298cb87b9b57470ee0b1f4336a9fa06c7b6ba#r27372661

**Comment by amorgun** [comment]
Pull request check would also be nice. I am looking at https://github.com/pixelogik/NearPy/pull/72 and cannot see test results there.

**Comment by pixelogik** [comment]
@amorgun Agreed. Pull request will not be merged with out tests. Pull request is currently in discussion anyway because of something else.
