### ISSUE TITLE
Support for generating and searching in L hash tables

### ISSUE THREAD

**Issue by adizhol** [pixelogik/NearPy#78]
Hi,
I didn't see this feature while experimenting with NearPy API, so apologies if I missed something...
As I understand NearPy.Engine creates a single LSH hash table. Most ANN algorithms use a number of hash tables to reduce false negative rates (missing a close neighbor).
Is it possible to create a simple API for this in NearPy?

Thanks!

**Comment by pixelogik** [comment]
Hi,

having multiple hash tables is actually the default use case with NearPy. The Engine constructor has the lshashes parameter, which takes an array of hash tables, each being an instance of a LSHash subclass/implementation. 

Best regards

**Comment by adizhol** [comment]
Hi @pixelogik,
so each RandomBinaryProjections() creates a single hash table?
And if I want 10 tables, I would do something like this:
```
hashes = [RandomBinaryProjections('rbp', 8) for _ in range(10)]
engine = Engine(dimension, lshashes=hashes, distance=CosineDistanceNormalized())

```
Thank you

**Comment by pixelogik** [comment]
Yes :)
