### ISSUE TITLE
Proposing a PR to fix a few small typos

### ISSUE THREAD

**Issue by timgates42** [pixelogik/NearPy#94]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate and Expected Behaviour

- Examine nearpy/hashes/permutation/hashpermutationmapper.py, nearpy/hashes/permutation/hashpermutations.py and observe `separatly`, however expect to see `separately`.
- Examine nearpy/filters/vectorfilter.py and observe `tupes`, however expect to see `tuples`.
- Examine nearpy/hashes/permutation/permutedIndex.py and observe `qurey`, however expect to see `query`.
- Examine nearpy/filters/uniquefilter.py and observe `listst`, however expect to see `lists`.
- Examine nearpy/hashes/randombinaryprojectiontree.py and observe `leafes`, however expect to see `leaves`.
- Examine README.md and observe `implementatiosn`, however expect to see `implementation`.
- Examine nearpy/hashes/permutation/hashpermutationmapper.py and observe `extact`, however expect to see `exact`.
- Examine nearpy/hashes/permutation/permutedIndex.py and observe `cloest`, however expect to see `closest`.

# Notes

Semi-automated issue generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

To avoid wasting CI processing resources a branch with the fix has been
prepared but a pull request has not yet been created. A pull request fixing
the issue can be prepared from the link below, feel free to create it or
request @timgates42 create the PR. Alternatively if the fix is undesired please
close the issue with a small comment about the reasoning.

https://github.com/timgates42/NearPy/pull/new/bugfix_typos

Thanks.

**Comment by pixelogik** [comment]
@timgates42 If you still have the time for it, could you please create the pull request? Thank you!

**Comment by timgates42** [comment]
thx @pixelogik created https://github.com/pixelogik/NearPy/pull/95
